name = "scanlake-store"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
ALLOWED_ORIGIN = "*"

[[r2_buckets]]
binding = "SCANLAKE_BUCKET"
bucket_name = "scanlake-data"

[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

# KV namespace for API key metadata.
[[kv_namespaces]]
binding = "API_KEYS"
id = "ac8fe738c3014c49b0a986af12af23f9"
preview_id = "b7c163bedd4644e8bd010e4d57252ca1"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]
